"""add test ingestion tables and project tokens

Revision ID: 77189536fe55
Revises: 6dd86ff0181e
Create Date: 2026-09-09 14:48:40.942012

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77189536fe55"
down_revision: str | Sequence[str] | None = "6dd86ff0181e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_run",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("project_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_run_project_id"), "test_run", ["project_id"], unique=False)
    op.create_table(
        "test_suite",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("project_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "file_path"),
    )
    op.create_index(op.f("ix_test_suite_project_id"), "test_suite", ["project_id"], unique=False)
    op.create_table(
        "test_case",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("suite_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("test_title", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["suite_id"], ["test_suite.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("suite_id", "test_title"),
    )
    op.create_index(op.f("ix_test_case_suite_id"), "test_case", ["suite_id"], unique=False)
    op.create_table(
        "test_result",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("run_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("case_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("PASSED", "FAILED", "SKIPPED", name="test_status"), nullable=False
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["case_id"], ["test_case.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["test_run.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_result_case_id"), "test_result", ["case_id"], unique=False)
    op.create_index(op.f("ix_test_result_run_id"), "test_result", ["run_id"], unique=False)
    op.add_column("project", sa.Column("token_hash", sa.String(length=64), nullable=True))
    op.add_column("project", sa.Column("token_last4", sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "token_last4")
    op.drop_column("project", "token_hash")
    op.drop_index(op.f("ix_test_result_run_id"), table_name="test_result")
    op.drop_index(op.f("ix_test_result_case_id"), table_name="test_result")
    op.drop_table("test_result")
    sa.Enum(name="test_status").drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f("ix_test_case_suite_id"), table_name="test_case")
    op.drop_table("test_case")
    op.drop_index(op.f("ix_test_suite_project_id"), table_name="test_suite")
    op.drop_table("test_suite")
    op.drop_index(op.f("ix_test_run_project_id"), table_name="test_run")
    op.drop_table("test_run")
    # ### end Alembic commands ###
